USE [master]
GO
/****** Object:  Database [sensitivewordsdb]    Script Date: 2025/10/04 12:58:45 ******/
CREATE DATABASE [sensitivewordsdb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'sensitivewordsdb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\sensitivewordsdb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'sensitivewordsdb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\sensitivewordsdb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [sensitivewordsdb] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [sensitivewordsdb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [sensitivewordsdb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [sensitivewordsdb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [sensitivewordsdb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [sensitivewordsdb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [sensitivewordsdb] SET ARITHABORT OFF 
GO
ALTER DATABASE [sensitivewordsdb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [sensitivewordsdb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [sensitivewordsdb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [sensitivewordsdb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [sensitivewordsdb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [sensitivewordsdb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [sensitivewordsdb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [sensitivewordsdb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [sensitivewordsdb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [sensitivewordsdb] SET  DISABLE_BROKER 
GO
ALTER DATABASE [sensitivewordsdb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [sensitivewordsdb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [sensitivewordsdb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [sensitivewordsdb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [sensitivewordsdb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [sensitivewordsdb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [sensitivewordsdb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [sensitivewordsdb] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [sensitivewordsdb] SET  MULTI_USER 
GO
ALTER DATABASE [sensitivewordsdb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [sensitivewordsdb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [sensitivewordsdb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [sensitivewordsdb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [sensitivewordsdb] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [sensitivewordsdb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [sensitivewordsdb] SET QUERY_STORE = ON
GO
ALTER DATABASE [sensitivewordsdb] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [sensitivewordsdb]
GO
/****** Object:  UserDefinedTableType [dbo].[ListOfWords]    Script Date: 2025/10/04 12:58:45 ******/
CREATE TYPE [dbo].[ListOfWords] AS TABLE(
	[Word] [nvarchar](100) NOT NULL
)
GO
/****** Object:  Table [dbo].[Metadata]    Script Date: 2025/10/04 12:58:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Metadata](
	[Key] [nvarchar](100) NOT NULL,
	[Value] [nvarchar](4000) NOT NULL,
	[UpdatedAtUtc] [datetime2](0) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Key] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SensitiveWord]    Script Date: 2025/10/04 12:58:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SensitiveWord](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Word] [nvarchar](255) NOT NULL,
	[IsActive] [bit] NOT NULL,
	[CreatedAtUtc] [datetime2](0) NOT NULL,
	[UpdatedAtUtc] [datetime2](0) NOT NULL,
	[IsDeleted] [bit] NOT NULL,
	[DeletedAtUtc] [datetime2](0) NULL,
 CONSTRAINT [PK__Sensitiv__3214EC07D4C3227F] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ__Sensitiv__95B501089755EE29] UNIQUE NONCLUSTERED 
(
	[Word] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UX_SensitiveWord_Word_Active]    Script Date: 2025/10/04 12:58:45 ******/
CREATE UNIQUE NONCLUSTERED INDEX [UX_SensitiveWord_Word_Active] ON [dbo].[SensitiveWord]
(
	[Word] ASC
)
WHERE ([IsDeleted]=(0))
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Metadata] ADD  DEFAULT (sysutcdatetime()) FOR [UpdatedAtUtc]
GO
ALTER TABLE [dbo].[SensitiveWord] ADD  CONSTRAINT [DF__Sensitive__IsAct__38996AB5]  DEFAULT ((1)) FOR [IsActive]
GO
ALTER TABLE [dbo].[SensitiveWord] ADD  CONSTRAINT [DF__Sensitive__Creat__398D8EEE]  DEFAULT (sysutcdatetime()) FOR [CreatedAtUtc]
GO
ALTER TABLE [dbo].[SensitiveWord] ADD  CONSTRAINT [DF_SensitiveWord_UpdatedAtUtc]  DEFAULT (sysutcdatetime()) FOR [UpdatedAtUtc]
GO
ALTER TABLE [dbo].[SensitiveWord] ADD  CONSTRAINT [DF__Sensitive__IsDel__440B1D61]  DEFAULT ((0)) FOR [IsDeleted]
GO
USE [master]
GO
ALTER DATABASE [sensitivewordsdb] SET  READ_WRITE 
GO
